/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: 'Start',
      items: ['start/getting-started','start/installation','start/where-to-start', 'concept/cli'],
    },
    {
      type: "category",
      label: 'Concept',
      items: ['concept/bucket','concept/passport','concept/function','concept/storage','concept/dashboard','concept/user-activities','concept/webhook','concept/l10n','concept/asset-store', 'concept/orm'],
    },
    {
      type: "category",
      label: 'Guide',
      items: ['guide/contributing','guide/open-source-build','guide/user-register-login'],
    },
    {
      type: "category",
      label: 'Additionals',
      items: ['additionals/bucket-module-types','additionals/query-params','additionals/access-control-rules'],
    },
    {
      type: "category",
      label: 'Libraries',
      items: ['libraries/bucket-module','libraries/database-module','libraries/identity-module','libraries/storage-module'],
    },

    // {
    //   type: "category",
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],

};

module.exports = sidebars;
